JDBC_URL: "jdbc:drill:drillbit=drill:31010"

#WORKING_DIRECTORY: "/data/hgnc/hgnc_complete_set.txt"
WORKING_DIRECTORY: "/data/hgnc"

JDBC_CONTAINER: "drill"
JDBC_USERNAME: "postgres"
JDBC_PASSWORD: "pwd"

GRAPHDB_URL: "http://graphdb.dumontierlab.com"
GRAPHDB_REPOSITORY: "test"

GRAPHDB_USERNAME: "import_user" 
GRAPHDB_PASSWORD: "test"
