JDBC_URL: "jdbc:drill:drillbit=drill:31010"

# "jdbc:postgresql://postgres:5432/drugcentral"

#WORKING_DIRECTORY: "/data/ncats/hgnc/hgnc_complete_set.txt"
WORKING_DIRECTORY: "/data/ncats/drugbank/full_database.xml"

BASE_URI: "http://data2services/"

JDBC_CONTAINER: "drill"
JDBC_USERNAME: "postgres"
JDBC_PASSWORD: "pwd"

#GRAPHDB_URL: "http://graphdb.dumontierlab.com/"
GRAPHDB_URL: "http://graphdb:7200"
GRAPHDB_REPOSITORY: "test"

GRAPHDB_USERNAME: "import_user" 
GRAPHDB_PASSWORD: "test"
