JDBC_URL: "jdbc:postgresql://postgres:5432/drugcentral"

WORKING_DIRECTORY: "/data/kraken/download/kraken-download/datasets/pubmed/baseline/pubmed18n0002.xml.gz"

JDBC_CONTAINER: "postgres"
JDBC_USERNAME: "postgres"
JDBC_PASSWORD: "pwd"

GRAPHDB_URL: "http://graphdb:7200"
GRAPHDB_REPOSITORY: "test"
GRAPHDB_USERNAME: "import_user" 
GRAPHDB_PASSWORD: "test"